### ISSUE TITLE
Cool project but I can deploy to my own Cloudflare workers

### ISSUE THREAD

**Issue by luispuerto** [chrisns/linkedin-newsletter-rss#46]
Sorry, I'm a little bit of a noob on this, but I can't deploy to my own Cloudflare workers. It I use the deploy button I reach a dead end when I have to activate GitHub workflows on my fork. I do that, but the wrangler is not able to detect it anyway. 

If I c&p the `index.js` to a Cloudflare worker is telling me that it can't import cheerio. 

Can you help with this a little bit?

**Comment by chrisns** [comment]
hi,
Sorry for being slow to reply.
I'm not really sure to be honest what the journey for deploying yourself to a cloudflare worker looks like having not done it before.
If you're going to do it fully manually you'll need to bundle with the dependencies.

**Comment by chrisns** [comment]
Ah wicked, cool! If you make changes/improvements, then pull requests are very welcome!
Thanks
Chris
